"""Per-commit project-map persistence.

The map itself is **generated by ember-server** during the indexing
pass that produces per-entity summaries. It arrives in the JSONL
changeset as a :class:`CommitSummaryOp`; ``apply_delta`` calls
:meth:`ProjectMap.write` to persist it next to the chroma for the
matching commit.

This module owns path resolution and disk persistence only. There is
no client-side LLM rendering — the server is the single source of
truth so every developer indexing the same commit sees the same map,
the cost is paid once instead of once per developer, and the agent's
high-level overview is always available regardless of whether the
client has API credentials configured.

A missing map is handled gracefully by the session loader (the agent
just doesn't get a ``## Project Map`` section).
"""

from __future__ import annotations

import logging
from functools import cached_property
from pathlib import Path

from ember_code.core.code_index.paths import code_index_dir

logger = logging.getLogger(__name__)


class ProjectMap:
    """Filesystem adapter for the per-commit project map.

    Not a Pydantic schema — this is a plain class because it wraps
    disk I/O, not a serialised payload. The class is a small
    OOP-shaped seam over the ``(project, commit_sha, data_dir)``
    triple that all three operations share, plus a place to hang
    future GC-coupling behaviours the module docstring already
    advertises.

    Instances are **immutable by convention**: :attr:`path` is a
    :func:`cached_property` that assumes the three constructor args
    never change. Do not add setters or mutate the underlying
    attributes — build a new instance instead.
    """

    def __init__(
        self,
        project: str | Path,
        commit_sha: str,
        *,
        data_dir: str | Path = "~/.ember",
    ) -> None:
        self._project = project
        self._commit_sha = commit_sha
        self._data_dir = data_dir

    @cached_property
    def path(self) -> Path:
        """Where the map for this commit lives on disk.

        Sits next to the per-commit chroma dir so the two are
        paired and can be GC'd together (when the chroma is
        cleaned for a stale commit, the map can be removed
        alongside via :meth:`delete`).
        """
        return (
            code_index_dir(self._project, data_dir=self._data_dir)
            / f"{self._commit_sha}.project_map.md"
        )

    def write(self, markdown: str) -> Path:
        """Persist server-rendered markdown to disk and return the path.

        Called from ``apply_delta`` when a :class:`CommitSummaryOp`
        arrives in the changeset. The markdown is taken as-is — no
        post-processing, no validation, no truncation — because the
        server's output is the canonical form. If the server emitted
        garbage, the agent gets garbage; we don't paper over
        upstream issues here.
        """
        path = self.path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(markdown, encoding="utf-8")
        logger.info(
            "Project map persisted: %s (%d bytes, server-supplied)",
            path,
            len(markdown.encode("utf-8")),
        )
        return path

    def load(self) -> str | None:
        """Read the map from disk if present. ``None`` if missing.

        Called by the session loader to inject the map into the
        agent's system prompt. A missing map is non-fatal — the
        agent works without it.
        """
        path = self.path
        if not path.is_file():
            return None
        try:
            return path.read_text(encoding="utf-8")
        except OSError as e:
            logger.warning("Failed to read project map %s: %s", path, e)
            return None

    def exists(self) -> bool:
        """``True`` if a map is on disk for this commit."""
        return self.path.is_file()

    def delete(self) -> None:
        """Remove the map file if present.

        Provided for the GC-coupling case the module docstring
        promises: when a stale commit's chroma is cleaned, the
        matching map should be removed alongside. ``missing_ok=True``
        so calling delete on a commit that never had a map is a
        no-op rather than an error.
        """
        self.path.unlink(missing_ok=True)
