"""Per-commit project-map persistence.

The map itself is **generated by ember-server** during the indexing
pass that produces per-entity summaries. It arrives in the JSONL
changeset as a :class:`CommitSummaryOp`; ``apply_delta`` calls
:func:`write_server_supplied_map` to persist it next to the chroma
for the matching commit.

This module owns path resolution and disk persistence only. There is
no client-side LLM rendering — the server is the single source of
truth so every developer indexing the same commit sees the same map,
the cost is paid once instead of once per developer, and the agent's
high-level overview is always available regardless of whether the
client has API credentials configured.

A missing map is handled gracefully by the session loader (the agent
just doesn't get a ``## Project Map`` section).
"""

from __future__ import annotations

import logging
from pathlib import Path

from ember_code.core.code_index.paths import code_index_dir

logger = logging.getLogger(__name__)


def project_map_path(
    project: str | Path,
    commit_sha: str,
    *,
    data_dir: str | Path = "~/.ember",
) -> Path:
    """Where the map for a given commit lives on disk.

    Sits next to the per-commit chroma dir so the two are paired and
    can be GC'd together (when the chroma is pruned for a stale
    commit, the map can be removed alongside).
    """
    return code_index_dir(project, data_dir=data_dir) / f"{commit_sha}.project_map.md"


def write_server_supplied_map(
    *,
    project: str | Path,
    data_dir: str | Path,
    commit_sha: str,
    markdown: str,
) -> Path:
    """Persist server-rendered markdown to disk and return the path.

    Called from ``apply_delta`` when a :class:`CommitSummaryOp` arrives
    in the changeset. The markdown is taken as-is — no post-processing,
    no validation, no truncation — because the server's output is the
    canonical form. If the server emitted garbage, the agent gets
    garbage; we don't paper over upstream issues here.
    """
    path = project_map_path(project, commit_sha, data_dir=data_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    logger.info(
        "Project map persisted: %s (%d bytes, server-supplied)",
        path, len(markdown.encode("utf-8")),
    )
    return path


def load_project_map(
    project: str | Path,
    commit_sha: str,
    *,
    data_dir: str | Path = "~/.ember",
) -> str | None:
    """Read the map from disk if present. ``None`` if missing.

    Called by the session loader to inject the map into the agent's
    system prompt. A missing map is non-fatal — the agent works
    without it.
    """
    path = project_map_path(project, commit_sha, data_dir=data_dir)
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except OSError as e:
        logger.warning("Failed to read project map %s: %s", path, e)
        return None
