"""System-prompt assembly stage.

Owns the base system prompt loaded from ``core/prompts/``: picks
the CodeIndex variant when available, substitutes the ``{{AGENT_
CATALOG}}`` placeholder from the agent pool's catalog, appends the
per-commit Project Map (best-effort — missing map is non-fatal),
and tacks on the skill-descriptions block when skills are
configured to auto-trigger.

The output is a single string handed to
:class:`InstructionsBuilder` as the first entry of the
``instructions`` list.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from pathlib import Path
from typing import Any

from ember_code.core.code_index.manifest import Manifest
from ember_code.core.code_index.project_map import ProjectMap

logger = logging.getLogger(__name__)


class PromptBuilder:
    """Render the main-agent system prompt.

    :meth:`render` is the only public entry point — the smaller
    helpers exist so each substitution step is testable in
    isolation and the render sequence reads as a short list of
    named phases.
    """

    def __init__(
        self,
        *,
        project_dir: Path,
        settings: Any,
        codeindex_available: bool,
        agent_catalog: str,
        skill_descriptions: str,
        prompt_loader: Callable[[str], str],
    ) -> None:
        self._project_dir = project_dir
        self._settings = settings
        self._codeindex_available = codeindex_available
        self._agent_catalog = agent_catalog
        self._skill_descriptions = skill_descriptions
        self._prompt_loader = prompt_loader

    def load_base(self) -> str:
        """Pick + load the base template.

        When CodeIndex is available we load
        ``main_agent.codeindex.md`` — a wholly CodeIndex-first
        variant with the tool reference inline and read-before-
        edit / search guidance re-framed around the index. The
        ``{{CODEINDEX_TOOLS}}`` placeholder only exists in the
        plain variant; for the codeindex variant the replacement
        is a no-op.
        """
        name = "main_agent.codeindex" if self._codeindex_available else "main_agent"
        return self._prompt_loader(name)

    def substitute_placeholders(self, prompt: str) -> str:
        """Substitute ``{{AGENT_CATALOG}}`` + ``{{CODEINDEX_TOOLS}}``."""
        catalog = self._agent_catalog or "(no agents loaded)"
        prompt = prompt.replace("{{AGENT_CATALOG}}", catalog)
        prompt = prompt.replace("{{CODEINDEX_TOOLS}}", "")
        return prompt

    def append_project_map(self, prompt: str) -> str:
        """Append the per-commit Project Map (best-effort).

        Auto-generated by ``apply_delta``; gives the agent a
        factual overview (taxonomy, tables, cached-resource
        wrappers, vocabulary glossary, entry points) before it
        issues a single tool call. Missing map is non-fatal — the
        prompt still works without it.
        """
        if not self._codeindex_available:
            return prompt
        try:
            manifest = Manifest(
                project=self._project_dir,
                data_dir=self._settings.storage.data_dir,
            )
            head_sha = manifest.load().head
            if not head_sha:
                return prompt
            map_md = ProjectMap(
                self._project_dir,
                head_sha,
                data_dir=self._settings.storage.data_dir,
            ).load()
            if map_md:
                return prompt + "\n\n## Project Map\n\n" + map_md
        except (FileNotFoundError, PermissionError, OSError, ValueError) as exc:
            # Missing / unreadable manifest / bad JSON — project map
            # is optional, degrade silently. Anything else (AttributeError,
            # TypeError, etc.) is a programming bug and should surface.
            logger.debug("project-map append failed: %s", exc)
        return prompt

    def append_skills(self, prompt: str) -> str:
        """Append skill descriptions when auto-trigger is on."""
        if not self._skill_descriptions:
            return prompt
        if not self._settings.skills.auto_trigger:
            return prompt
        return (
            prompt
            + "\n\n## Available Skills (user can invoke via /name)\n"
            + self._skill_descriptions
        )

    def render(self) -> str:
        """Compose the full prompt through the four phases."""
        prompt = self.load_base()
        prompt = self.substitute_placeholders(prompt)
        prompt = self.append_project_map(prompt)
        prompt = self.append_skills(prompt)
        return prompt
